version: 1

konstellio:

  server:
    host: localhost
    port: 8080

  database:
    driver: sqlite
    filename: blog.sqlite

  fs:
    driver: local
    root: ./
  
  cache:
    driver: memory

  mq:
    driver: memory

  locales:
    en: 'English'
    fr: 'French'

  plugins:
    - ./blog.js