version: 1

sculptor:

  server:
    host: localhost
    port: 8080

  database:
    driver: sqlite
    filename: mock://memory

  fs:
    driver: local
    root: ./
  
  cache:
    driver: memory

  mq:
    driver: memory